re-writing user-story for parametric use, done with cmd_list

diff --git a/git-flow-user-story-o b/git-flow-user-story-o
--- a/git-flow-user-story-o
+++ b/git-flow-user-story-o
@@ -36,23 +36,21 @@
 # policies, either expressed or implied, of Vincent Driessen.
 #
 
-init() {
-  require_git_repo
-  require_gitflow_initialized
-  gitflow_load_settings
-  PREFIX=$(git config --get gitflow.prefix.user-story)
-}
+require_git_repo
+require_gitflow_initialized
+gitflow_load_settings
+PREFIX=$(git config --get gitflow.prefix.user-story)
 
 usage() {
-	#echo "usage: git flow user-story [list] [-v]"
+    #echo "usage: git flow user-story [list] [-v]"
 	echo "       git flow user-story start [-F] <name> [<base>]"
-	echo "       git flow user-story finish [-rFkDS] [<name|nameprefix>]"
+	echo "       git flow user-story finish [-rFk] <name|nameprefix>"
 	echo "       git flow user-story publish <name>"
 	#echo "       git flow user-story track <name>"
 	#echo "       git flow user-story diff [<name|nameprefix>]"
 	#echo "       git flow user-story rebase [-i] [<name|nameprefix>]"
 	#echo "       git flow user-story checkout [<name|nameprefix>]"
-	#echo "       git flow user-story pull [-r] <remote> [<name>]"
+	#echo "       git flow user-story pull <remote> [<name>]"
 }
 
 cmd_default() {
@@ -63,11 +61,11 @@ cmd_list() {
 	DEFINE_boolean verbose false 'verbose (more) output' v
 	parse_args "$@"
 
-	local user_story_branches
+	local user-story_branches
 	local current_branch
 	local short_names
-	user_story_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	if [ -z "$user_story_branches" ]; then
+	user-story_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+	if [ -z "$user-story_branches" ]; then
 		warn "No user-story branches exist."
 		warn ""
 		warn "You can start a new user-story branch:"
@@ -77,7 +75,7 @@ cmd_list() {
 		exit 0
 	fi
 	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
-	short_names=$(echo "$user_story_branches" | sed "s ^$PREFIX  g")
+	short_names=$(echo "$user-story_branches" | sed "s ^$PREFIX  g")
 
 	# determine column width first
 	local width=0
@@ -91,8 +89,8 @@ cmd_list() {
 	local branch
 	for branch in $short_names; do
 		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$TARGET")
-		local target_sha=$(git rev-parse "$TARGET")
+		local base=$(git merge-base "$fullname" "$current_branch")
+		local feature_sha=$(git rev-parse "$current_branch")
 		local branch_sha=$(git rev-parse "$fullname")
 		if [ "$fullname" = "$current_branch" ]; then
 			printf "* "
@@ -101,12 +99,12 @@ cmd_list() {
 		fi
 		if flag verbose; then
 			printf "%-${width}s" "$branch"
-			if [ "$branch_sha" = "$target_sha" ]; then
+			if [ "$branch_sha" = "$feature_sha" ]; then
 				printf "(no commits yet)"
 			elif [ "$base" = "$branch_sha" ]; then
-				printf "(is behind $TARGET, may ff)"
-			elif [ "$base" = "$target_sha" ]; then
-				printf "(based on latest %TARGET)"
+				printf "(is behind your feature branch, may ff)"
+			elif [ "$base" = "$feature_sha" ]; then
+				printf "(based on latest feature branch)"
 			else
 				printf "(may be rebased)"
 			fi
@@ -145,13 +143,13 @@ expand_nameprefix_arg() {
 	esac
 }
 
-use_current_feature_branch_name() {
+use_current_user_story_branch_name() {
 	local current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
 		BRANCH=$current_branch
 		NAME=${BRANCH#$PREFIX}
 	else
-		warn "The current HEAD is no feature branch."
+		warn "The current HEAD is no user-story branch."
 		warn "Please specify a <name> argument."
 		exit 1
 	fi
@@ -162,13 +160,13 @@ expand_nameprefix_arg_or_current() {
 		expand_nameprefix_arg
 		require_branch "$PREFIX$NAME"
 	else
-		use_current_feature_branch_name
+		use_current_user_story_branch_name
 	fi
 }
 
 name_or_current() {
 	if [ -z "$NAME" ]; then
-		use_current_feature_branch_name
+		use_current_user_story_branch_name
 	fi
 }
 
@@ -179,7 +177,6 @@ parse_args() {
 
 	# read arguments into global variables
 	NAME=$1
-    TARGET=$2
 	BRANCH=$PREFIX$NAME
 }
 
@@ -197,26 +194,27 @@ parse_remote_name() {
 cmd_start() {
 	DEFINE_boolean fetch false 'fetch from origin before performing local operation' F
 	parse_args "$@"
-	BASE=${2:-$DEVELOP_BRANCH}
 	require_name_arg
+	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
+	BASE=$current_branch
 
 	# sanity checks
 	require_branch_absent "$BRANCH"
 
 	# update the local repo with remote changes, if asked
 	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+		git fetch -q "$ORIGIN" "$current_branch"
 	fi
 
 	# if the origin branch counterpart exists, assert that the local branch
 	# isn't behind it (to avoid unnecessary rebasing)
-	if git_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	if git_branch_exists "$ORIGIN/$current_branch"; then
+		require_branches_equal "$current_branch" "$ORIGIN/$current_branch"
 	fi
 
 	# create branch
-	if ! git_do checkout -b "$BRANCH" "$BASE"; then
-		die "Could not create feature branch '$BRANCH'"
+	if ! git checkout -b "$BRANCH" "$BASE"; then
+		die "Could not create user-story branch '$BRANCH'"
 	fi
 
 	echo
@@ -224,9 +222,9 @@ cmd_start() {
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
 	echo "- You are now on branch '$BRANCH'"
 	echo ""
-	echo "Now, start committing on your feature. When done, use:"
+	echo "Now, start committing on your user-story. When done, use:"
 	echo ""
-	echo "     git flow feature finish $NAME"
+	echo "     git flow user-story finish $NAME"
 	echo
 }
 
@@ -234,10 +232,8 @@ cmd_finish() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean rebase false "rebase instead of merge" r
 	DEFINE_boolean keep false "keep branch after performing finish" k
-	DEFINE_boolean force_delete false "force delete feature branch after finish" D
-	DEFINE_boolean squash false "squash feature during merge" S
 	parse_args "$@"
-	expand_nameprefix_arg_or_current
+	expand_nameprefix_arg
 
 	# sanity checks
 	require_branch "$BRANCH"
@@ -276,7 +272,7 @@ cmd_finish() {
 			echo "    git commit"
 			echo 
 			echo "You can then complete the finish by running it again:"
-			echo "    git flow feature finish $NAME"
+			echo "    git flow user-story finish $NAME"
 			echo
 			exit 1
 		fi
@@ -285,63 +281,62 @@ cmd_finish() {
 	# sanity checks
 	require_clean_working_tree
 
+    #TODO somehow extract the branch you want to merge
+    printf "Feature branch that you want to merge into: "
+    read answer
+    printf "\n"
+    target_branch="feature/$answer"
+
 	# update local repo with remote changes first, if asked
-	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+	if has "$ORIGIN/$target_branch" "$(git_remote_branches)"; then
 		if flag fetch; then
-			git_do fetch -q "$ORIGIN" "$BRANCH"
-			git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+			git fetch -q "$ORIGIN" "$BRANCH"
 		fi
 	fi
 
-	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+	if has "$ORIGIN/$BRANCH" "$(git_remote_branches)"; then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	if has "$ORIGIN/$target_branch" "$(git_remote_branches)"; then
+		require_branches_equal "$target_branch" "$ORIGIN/$target_branch"
 	fi
 
 	# if the user wants to rebase, do that first
 	if flag rebase; then
-		if ! git flow feature rebase "$NAME" "$DEVELOP_BRANCH"; then
+		if ! git flow user-story rebase "$NAME" "$target_branch"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
-			warn "    git flow feature finish '$NAME' '$DEVELOP_BRANCH'"
+			warn "    git flow user-story finish '$NAME' '$target_branch'"
 			exit 1
 		fi
 	fi
 
 	# merge into BASE
-	git_do checkout "$DEVELOP_BRANCH"
-	if [ "$(git rev-list -n2 "$DEVELOP_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
-		git_do merge --ff "$BRANCH"
+	git checkout "$target_branch"
+	if [ "$(git rev-list -n2 "$target_branch..$BRANCH" | wc -l)" -eq 1 ]; then
+		git merge --ff "$BRANCH"
 	else
-		if noflag squash; then
-		    git_do merge --no-ff "$BRANCH"
-		else
-			git_do merge --squash "$BRANCH"
-			git_do commit
-			git_do merge "$BRANCH"
-		fi
+		git merge --no-ff "$BRANCH"
 	fi
 
 	if [ $? -ne 0 ]; then
 		# oops.. we have a merge conflict!
-		# write the given $DEVELOP_BRANCH to a temporary file (we need it later)
+		# write the given $target_branch to a temporary file (we need it later)
 		mkdir -p "$DOT_GIT_DIR/.gitflow"
-		echo "$DEVELOP_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+		echo "$target_branch" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
 		echo
 		echo "There were merge conflicts. To resolve the merge conflict manually, use:"
 		echo "    git mergetool"
 		echo "    git commit"
 		echo 
 		echo "You can then complete the finish by running it again:"
-		echo "    git flow feature finish $NAME"
+		echo "    git flow user-story finish $NAME"
 		echo
 		exit 1
 	fi
 
-	# when no merge conflict is detected, just clean up the feature branch
+	# when no merge conflict is detected, just clean up the user-story branch
 	helper_finish_cleanup
 }
 
@@ -352,28 +347,24 @@ helper_finish_cleanup() {
 
 	# delete branch
 	if flag fetch; then
-		git_do push "$ORIGIN" ":refs/heads/$BRANCH"
+		git push "$ORIGIN" ":refs/heads/$BRANCH"
 	fi
 	
 	
 	if noflag keep; then
-		if flag force_delete; then
-			git_do branch -D "$BRANCH"
-		else
-			git_do branch -d "$BRANCH"
-		fi
+		git branch -d "$BRANCH"
 	fi
 
 	echo
 	echo "Summary of actions:"
-	echo "- The feature branch '$BRANCH' was merged into '$DEVELOP_BRANCH'"
+	echo "- The User Story branch '$BRANCH' was merged into '$target_branch'"
 	#echo "- Merge conflicts were resolved"		# TODO: Add this line when it's supported
 	if flag keep; then
-		echo "- Feature branch '$BRANCH' is still available"
+		echo "- User Story branch '$BRANCH' is still available"
 	else
-		echo "- Feature branch '$BRANCH' has been removed"
+		echo "- User Story branch '$BRANCH' has been removed"
 	fi
-	echo "- You are now on branch '$DEVELOP_BRANCH'"
+	echo "- You are now on branch '$target_branch)"
 	echo
 }
 
@@ -384,17 +375,17 @@ cmd_publish() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch "$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git fetch -q "$ORIGIN"
 	require_branch_absent "$ORIGIN/$BRANCH"
 
 	# create remote branch
-	git_do push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH"
+	git fetch -q "$ORIGIN"
 
 	# configure remote tracking
-	git_do config "branch.$BRANCH.remote" "$ORIGIN"
-	git_do config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
-	git_do checkout "$BRANCH"
+	git config "branch.$BRANCH.remote" "$ORIGIN"
+	git config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
+	git checkout "$BRANCH"
 
 	echo
 	echo "Summary of actions:"
@@ -411,11 +402,11 @@ cmd_track() {
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	git_do fetch -q "$ORIGIN"
+	git fetch -q "$ORIGIN"
 	require_branch "$ORIGIN/$BRANCH"
 
 	# create tracking branch
-	git_do checkout -b "$BRANCH" "$ORIGIN/$BRANCH"
+	git checkout -b "$BRANCH" "$ORIGIN/$BRANCH"
 
 	echo
 	echo "Summary of actions:"
@@ -429,14 +420,14 @@ cmd_diff() {
 
 	if [ "$NAME" != "" ]; then
 		expand_nameprefix_arg
-		BASE=$(git merge-base "$DEVELOP_BRANCH" "$BRANCH")
+		BASE=$(git merge-base "$current_branch" "$BRANCH")
 		git diff "$BASE..$BRANCH"
 	else
 		if ! git_current_branch | grep -q "^$PREFIX"; then
-			die "Not on a feature branch. Name one explicitly."
+			die "Not on a user-story branch. Name one explicitly."
 		fi
 
-		BASE=$(git merge-base "$DEVELOP_BRANCH" HEAD)
+		BASE=$(git merge-base "$current_branch" HEAD)
 		git diff "$BASE"
 	fi
 }
@@ -446,9 +437,9 @@ cmd_checkout() {
 
 	if [ "$NAME" != "" ]; then
 		expand_nameprefix_arg
-		git_do checkout "$BRANCH"
+		git checkout "$BRANCH"
 	else
-		die "Name a feature branch explicitly."
+		die "Name a user-story branch explicitly."
 	fi
 }
 
@@ -465,12 +456,12 @@ cmd_rebase() {
 	require_clean_working_tree
 	require_branch "$BRANCH"
 
-	git_do checkout -q "$BRANCH"
+	git checkout -q "$BRANCH"
 	local OPTS=
 	if flag interactive; then
 		OPTS="$OPTS -i"
 	fi
-	git_do rebase $OPTS "$DEVELOP_BRANCH"
+	git rebase $OPTS "$current_branch"
 }
 
 avoid_accidental_cross_branch_action() {
@@ -484,8 +475,7 @@ avoid_accidental_cross_branch_action() {
 }
 
 cmd_pull() {
-	#DEFINE_string prefix false 'alternative remote feature branch name prefix' p
-	DEFINE_boolean rebase false "pull with rebase" r
+	#DEFINE_string prefix false 'alternative remote user-story branch name prefix' p
 	parse_remote_name "$@"
 
 	if [ -z "$REMOTE" ]; then
@@ -493,12 +483,12 @@ cmd_pull() {
 	fi
 	name_or_current
 
-	# To avoid accidentally merging different feature branches into each other,
-	# die if the current feature branch differs from the requested $NAME
+	# To avoid accidentally merging different user-story branches into each other,
+	# die if the current user-story branch differs from the requested $NAME
 	# argument.
 	local current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
-		# we are on a local feature branch already, so $BRANCH must be equal to
+		# we are on a local user-story branch already, so $BRANCH must be equal to
 		# the current branch
 		avoid_accidental_cross_branch_action || die
 	fi
@@ -511,21 +501,13 @@ cmd_pull() {
 
 		# we already have a local branch called like this, so simply pull the
 		# remote changes in
-		if flag rebase; then
-			if ! git_do pull --rebase -q "$REMOTE" "$BRANCH"; then
-				warn "Pull was aborted. There might be conflicts during rebase or '$REMOTE' might be inaccessible."
-				exit 1
-			fi
-		else
-			git_do pull -q "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
-		fi
-
+		git pull -q "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
 		echo "Pulled $REMOTE's changes into $BRANCH."
 	else
 		# setup the local branch clone for the first time
-		git_do fetch -q "$REMOTE" "$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
-		git_do branch --no-track "$BRANCH" FETCH_HEAD || die "Branch failed."
-		git_do checkout -q "$BRANCH" || die "Checking out new local branch failed."
+		git fetch -q "$REMOTE" "$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
+		git branch --no-track "$BRANCH" FETCH_HEAD || die "Branch failed."
+		git checkout -q "$BRANCH" || die "Checking out new local branch failed."
 		echo "Created local branch $BRANCH based on $REMOTE's $BRANCH."
 	fi
 }
