i think i am done

diff --git a/git-flow-user-story b/git-flow-user-story
--- a/git-flow-user-story
+++ b/git-flow-user-story
@@ -48,11 +48,11 @@ usage() {
 	echo "       git flow user-story start [-F] <name> [<base>]"
 	echo "       git flow user-story finish [-rFkDS] [<name|nameprefix>]"
 	echo "       git flow user-story publish <name>"
-	#echo "       git flow user-story track <name>"
-	#echo "       git flow user-story diff [<name|nameprefix>]"
-	#echo "       git flow user-story rebase [-i] [<name|nameprefix>]"
-	#echo "       git flow user-story checkout [<name|nameprefix>]"
-	#echo "       git flow user-story pull [-r] <remote> [<name>]"
+    echo "       git flow user-story track <name>"
+    echo "       git flow user-story diff [<name|nameprefix>]"
+    echo "       git flow user-story rebase [-i] [<name|nameprefix>]"
+    echo "       git flow user-story checkout [<name|nameprefix>]"
+    echo "       git flow user-story pull [-r] <remote> [<name>]"
 }
 
 cmd_default() {
@@ -153,13 +153,13 @@ expand_nameprefix_arg() {
 	esac
 }
 
-use_current_feature_branch_name() {
+use_current_user-story_branch_name() {
 	local current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
 		BRANCH=$current_branch
 		NAME=${BRANCH#$PREFIX}
 	else
-		warn "The current HEAD is no feature branch."
+		warn "The current HEAD is no user-story branch."
 		warn "Please specify a <name> argument."
 		exit 1
 	fi
@@ -170,13 +170,13 @@ expand_nameprefix_arg_or_current() {
 		expand_nameprefix_arg
 		require_branch "$PREFIX$NAME"
 	else
-		use_current_feature_branch_name
+		use_current_user-story_branch_name
 	fi
 }
 
 name_or_current() {
 	if [ -z "$NAME" ]; then
-		use_current_feature_branch_name
+		use_current_user-story_branch_name
 	fi
 }
 
@@ -243,8 +243,8 @@ cmd_finish() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean rebase false "rebase instead of merge" r
 	DEFINE_boolean keep false "keep branch after performing finish" k
-	DEFINE_boolean force_delete false "force delete feature branch after finish" D
-	DEFINE_boolean squash false "squash feature during merge" S
+	DEFINE_boolean force_delete false "force delete user-story branch after finish" D
+	DEFINE_boolean squash false "squash user-story during merge" S
 	parse_args "$@"
 	expand_nameprefix_arg_or_current
 
@@ -285,7 +285,7 @@ cmd_finish() {
 			echo "    git commit"
 			echo 
 			echo "You can then complete the finish by running it again:"
-			echo "    git flow feature finish $NAME"
+			echo "    git flow user-story finish $NAME $TARGET_BRANCH"
 			echo
 			exit 1
 		fi
@@ -298,31 +298,31 @@ cmd_finish() {
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
 		if flag fetch; then
 			git_do fetch -q "$ORIGIN" "$BRANCH"
-			git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+			git_do fetch -q "$ORIGIN" "$TARGET_BRANCH"
 		fi
 	fi
 
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
 	fi
-	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+	if has "$ORIGIN/$TARGET_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$TARGET_BRANCH" "$ORIGIN/$TARGET_BRANCH"
 	fi
 
 	# if the user wants to rebase, do that first
 	if flag rebase; then
-		if ! git flow feature rebase "$NAME" "$DEVELOP_BRANCH"; then
+		if ! git flow user-story rebase "$NAME" "$TARGET_BRANCH"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
-			warn "    git flow feature finish '$NAME' '$DEVELOP_BRANCH'"
+			warn "    git flow user-story finish '$NAME' '$TARGET_BRANCH'"
 			exit 1
 		fi
 	fi
 
 	# merge into BASE
-	git_do checkout "$DEVELOP_BRANCH"
-	if [ "$(git rev-list -n2 "$DEVELOP_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
+	git_do checkout "$TARGET_BRANCH"
+	if [ "$(git rev-list -n2 "$TARGET_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
 		git_do merge --ff "$BRANCH"
 	else
 		if noflag squash; then
@@ -336,21 +336,21 @@ cmd_finish() {
 
 	if [ $? -ne 0 ]; then
 		# oops.. we have a merge conflict!
-		# write the given $DEVELOP_BRANCH to a temporary file (we need it later)
+		# write the given $TARGET_BRANCH to a temporary file (we need it later)
 		mkdir -p "$DOT_GIT_DIR/.gitflow"
-		echo "$DEVELOP_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+		echo "$TARGET_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
 		echo
 		echo "There were merge conflicts. To resolve the merge conflict manually, use:"
 		echo "    git mergetool"
 		echo "    git commit"
 		echo 
 		echo "You can then complete the finish by running it again:"
-		echo "    git flow feature finish $NAME"
+		echo "    git flow user-story finish $NAME $TARGET_BRANCH"
 		echo
 		exit 1
 	fi
 
-	# when no merge conflict is detected, just clean up the feature branch
+	# when no merge conflict is detected, just clean up the user-story branch
 	helper_finish_cleanup
 }
 
@@ -375,14 +375,14 @@ helper_finish_cleanup() {
 
 	echo
 	echo "Summary of actions:"
-	echo "- The feature branch '$BRANCH' was merged into '$DEVELOP_BRANCH'"
+	echo "- The user-story branch '$BRANCH' was merged into '$TARGET_BRANCH'"
 	#echo "- Merge conflicts were resolved"		# TODO: Add this line when it's supported
 	if flag keep; then
 		echo "- Feature branch '$BRANCH' is still available"
 	else
 		echo "- Feature branch '$BRANCH' has been removed"
 	fi
-	echo "- You are now on branch '$DEVELOP_BRANCH'"
+	echo "- You are now on branch '$TARGET_BRANCH'"
 	echo
 }
 
@@ -438,14 +438,14 @@ cmd_diff() {
 
 	if [ "$NAME" != "" ]; then
 		expand_nameprefix_arg
-		BASE=$(git merge-base "$DEVELOP_BRANCH" "$BRANCH")
+		BASE=$(git merge-base "$TARGET_BRANCH" "$BRANCH")
 		git diff "$BASE..$BRANCH"
 	else
 		if ! git_current_branch | grep -q "^$PREFIX"; then
-			die "Not on a feature branch. Name one explicitly."
+			die "Not on a user-story branch. Name one explicitly."
 		fi
 
-		BASE=$(git merge-base "$DEVELOP_BRANCH" HEAD)
+		BASE=$(git merge-base "$TARGET_BRANCH" HEAD)
 		git diff "$BASE"
 	fi
 }
@@ -457,7 +457,7 @@ cmd_checkout() {
 		expand_nameprefix_arg
 		git_do checkout "$BRANCH"
 	else
-		die "Name a feature branch explicitly."
+		die "Name a user-story branch explicitly."
 	fi
 }
 
@@ -479,7 +479,7 @@ cmd_rebase() {
 	if flag interactive; then
 		OPTS="$OPTS -i"
 	fi
-	git_do rebase $OPTS "$DEVELOP_BRANCH"
+	git_do rebase $OPTS "$TARGET_BRANCH"
 }
 
 avoid_accidental_cross_branch_action() {
@@ -493,7 +493,7 @@ avoid_accidental_cross_branch_action() {
 }
 
 cmd_pull() {
-	#DEFINE_string prefix false 'alternative remote feature branch name prefix' p
+	#DEFINE_string prefix false 'alternative remote user-story branch name prefix' p
 	DEFINE_boolean rebase false "pull with rebase" r
 	parse_remote_name "$@"
 
@@ -502,12 +502,12 @@ cmd_pull() {
 	fi
 	name_or_current
 
-	# To avoid accidentally merging different feature branches into each other,
-	# die if the current feature branch differs from the requested $NAME
+	# To avoid accidentally merging different user-story branches into each other,
+	# die if the current user-story branch differs from the requested $NAME
 	# argument.
 	local current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
-		# we are on a local feature branch already, so $BRANCH must be equal to
+		# we are on a local user-story branch already, so $BRANCH must be equal to
 		# the current branch
 		avoid_accidental_cross_branch_action || die
 	fi
