done with list and start for sure

diff --git a/git-flow-user-story b/git-flow-user-story
--- a/git-flow-user-story
+++ b/git-flow-user-story
@@ -91,8 +91,8 @@ cmd_list() {
 	local branch
 	for branch in $short_names; do
 		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$TARGET")
-		local target_sha=$(git rev-parse "$TARGET")
+		local base=$(git merge-base "$fullname" "$TARGET_BRANCH")
+		local target_sha=$(git rev-parse "$TARGET_BRANCH")
 		local branch_sha=$(git rev-parse "$fullname")
 		if [ "$fullname" = "$current_branch" ]; then
 			printf "* "
@@ -104,7 +104,7 @@ cmd_list() {
 			if [ "$branch_sha" = "$target_sha" ]; then
 				printf "(no commits yet)"
 			elif [ "$base" = "$branch_sha" ]; then
-				printf "(is behind $TARGET, may ff)"
+				printf "(is behind $TARGET_BRANCH, may ff)"
 			elif [ "$base" = "$target_sha" ]; then
 				printf "(based on latest %TARGET)"
 			else
@@ -125,6 +125,14 @@ cmd_help() {
 require_name_arg() {
 	if [ "$NAME" = "" ]; then
 		warn "Missing argument <name>"
+		usage
+		exit 1
+	fi
+}
+
+require_target_arg() {
+	if [ "$TARGET_BRANCH" = "" ]; then
+		warn "Missing argument <target-branch>"
 		usage
 		exit 1
 	fi
@@ -179,7 +187,7 @@ parse_args() {
 
 	# read arguments into global variables
 	NAME=$1
-    TARGET=$2
+    TARGET_BRANCH=$2
 	BRANCH=$PREFIX$NAME
 }
 
@@ -197,26 +205,27 @@ parse_remote_name() {
 cmd_start() {
 	DEFINE_boolean fetch false 'fetch from origin before performing local operation' F
 	parse_args "$@"
-	BASE=${2:-$DEVELOP_BRANCH}
+	BASE=${2:-$TARGET_BRANCH}
 	require_name_arg
+	require_target_arg
 
 	# sanity checks
 	require_branch_absent "$BRANCH"
 
 	# update the local repo with remote changes, if asked
 	if flag fetch; then
-		git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+		git_do fetch -q "$ORIGIN" "$TARGET_BRANCH"
 	fi
 
 	# if the origin branch counterpart exists, assert that the local branch
 	# isn't behind it (to avoid unnecessary rebasing)
 	if git_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
-		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
+		require_branches_equal "$TARGET_BRANCH" "$ORIGIN/$TARGET_BRANCH"
 	fi
 
 	# create branch
 	if ! git_do checkout -b "$BRANCH" "$BASE"; then
-		die "Could not create feature branch '$BRANCH'"
+		die "Could not create user-story branch '$BRANCH'"
 	fi
 
 	echo
@@ -224,9 +233,9 @@ cmd_start() {
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
 	echo "- You are now on branch '$BRANCH'"
 	echo ""
-	echo "Now, start committing on your feature. When done, use:"
+	echo "Now, start committing on your user-story. When done, use:"
 	echo ""
-	echo "     git flow feature finish $NAME"
+	echo "     git flow user-story finish $NAME $TARGET_BRANCH"
 	echo
 }
 
